# Generated by Django 2.0.7 on 2018-07-27 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactsApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dateUpdated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
